server:
  port: 0

elasticjob:
  regCenter:
    serverLists: 192.168.70.58:2181
    #zookeeper 的ip:port
    #名命空间，自己定义就好了
    namespace: cong
  jobs:
    #你的这个定时任务名称，自定义名称
    myElasticJob:
      #定时任务的全路径名
      elasticJobClass: com.cong.elasticjobdemo.temo.MyJob
      #定时任务执行的cron表达式
      cron: 0/5 * * * * ?
      #分片数量
      shardingTotalCount: 10
